apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openclaw-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openclaw-helm.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
